# Generated by Django 3.0.7 on 2020-07-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dates',
            name='pdpend',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
